// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogoutUseCase creates a new instance of MockLogoutUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogoutUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogoutUseCase {
	mock := &MockLogoutUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogoutUseCase is an autogenerated mock type for the LogoutUseCase type
type MockLogoutUseCase struct {
	mock.Mock
}

type MockLogoutUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogoutUseCase) EXPECT() *MockLogoutUseCase_Expecter {
	return &MockLogoutUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockLogoutUseCase
func (_mock *MockLogoutUseCase) Execute(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLogoutUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLogoutUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockLogoutUseCase_Expecter) Execute(ctx any, token any) *MockLogoutUseCase_Execute_Call {
	return &MockLogoutUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, token)}
}

func (_c *MockLogoutUseCase_Execute_Call) Run(run func(ctx context.Context, token string)) *MockLogoutUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogoutUseCase_Execute_Call) Return(err error) *MockLogoutUseCase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLogoutUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockLogoutUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
