// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"

	"github.com/Karbbone/Graefik/apps/api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoginUseCase creates a new instance of MockLoginUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoginUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoginUseCase {
	mock := &MockLoginUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoginUseCase is an autogenerated mock type for the LoginUseCase type
type MockLoginUseCase struct {
	mock.Mock
}

type MockLoginUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoginUseCase) EXPECT() *MockLoginUseCase_Expecter {
	return &MockLoginUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockLoginUseCase
func (_mock *MockLoginUseCase) Execute(ctx context.Context, username string, password string) (*domain.Session, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Session); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockLoginUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockLoginUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockLoginUseCase_Expecter) Execute(ctx any, username any, password any) *MockLoginUseCase_Execute_Call {
	return &MockLoginUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, username, password)}
}

func (_c *MockLoginUseCase_Execute_Call) Run(run func(ctx context.Context, username string, password string)) *MockLoginUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockLoginUseCase_Execute_Call) Return(session *domain.Session, err error) *MockLoginUseCase_Execute_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockLoginUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*domain.Session, error)) *MockLoginUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
