// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"
	"time"

	"github.com/Karbbone/Graefik/apps/api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Create(ctx context.Context, session *domain.Session) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Session) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *domain.Session
func (_e *MockSessionRepository_Expecter) Create(ctx any, session any) *MockSessionRepository_Create_Call {
	return &MockSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *MockSessionRepository_Create_Call) Run(run func(ctx context.Context, session *domain.Session)) *MockSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Session
		if args[1] != nil {
			arg1 = args[1].(*domain.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Create_Call) Return(err error) *MockSessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session *domain.Session) error) *MockSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Delete(ctx context.Context, token string) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSessionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) Delete(ctx any, token any) *MockSessionRepository_Delete_Call {
	return &MockSessionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, token)}
}

func (_c *MockSessionRepository_Delete_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Delete_Call) Return(err error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, token string) error) *MockSessionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExpired provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) DeleteExpired(ctx context.Context, now time.Time) error {
	ret := _mock.Called(ctx, now)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) error); ok {
		r0 = returnFunc(ctx, now)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockSessionRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
//   - now time.Time
func (_e *MockSessionRepository_Expecter) DeleteExpired(ctx any, now any) *MockSessionRepository_DeleteExpired_Call {
	return &MockSessionRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx, now)}
}

func (_c *MockSessionRepository_DeleteExpired_Call) Run(run func(ctx context.Context, now time.Time)) *MockSessionRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_DeleteExpired_Call) Return(err error) *MockSessionRepository_DeleteExpired_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_DeleteExpired_Call) RunAndReturn(run func(ctx context.Context, now time.Time) error) *MockSessionRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// FindByToken provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) FindByToken(ctx context.Context, token string) (*domain.Session, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for FindByToken")
	}

	var r0 *domain.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Session, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Session); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSessionRepository_FindByToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByToken'
type MockSessionRepository_FindByToken_Call struct {
	*mock.Call
}

// FindByToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockSessionRepository_Expecter) FindByToken(ctx any, token any) *MockSessionRepository_FindByToken_Call {
	return &MockSessionRepository_FindByToken_Call{Call: _e.mock.On("FindByToken", ctx, token)}
}

func (_c *MockSessionRepository_FindByToken_Call) Run(run func(ctx context.Context, token string)) *MockSessionRepository_FindByToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_FindByToken_Call) Return(session *domain.Session, err error) *MockSessionRepository_FindByToken_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockSessionRepository_FindByToken_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.Session, error)) *MockSessionRepository_FindByToken_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExpiry provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) UpdateExpiry(ctx context.Context, token string, expiresAt time.Time) error {
	ret := _mock.Called(ctx, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExpiry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = returnFunc(ctx, token, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSessionRepository_UpdateExpiry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExpiry'
type MockSessionRepository_UpdateExpiry_Call struct {
	*mock.Call
}

// UpdateExpiry is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expiresAt time.Time
func (_e *MockSessionRepository_Expecter) UpdateExpiry(ctx any, token any, expiresAt any) *MockSessionRepository_UpdateExpiry_Call {
	return &MockSessionRepository_UpdateExpiry_Call{Call: _e.mock.On("UpdateExpiry", ctx, token, expiresAt)}
}

func (_c *MockSessionRepository_UpdateExpiry_Call) Run(run func(ctx context.Context, token string, expiresAt time.Time)) *MockSessionRepository_UpdateExpiry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSessionRepository_UpdateExpiry_Call) Return(err error) *MockSessionRepository_UpdateExpiry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSessionRepository_UpdateExpiry_Call) RunAndReturn(run func(ctx context.Context, token string, expiresAt time.Time) error) *MockSessionRepository_UpdateExpiry_Call {
	_c.Call.Return(run)
	return _c
}
