// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"

	"github.com/Karbbone/Graefik/apps/api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// FindAll provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) FindAll(ctx context.Context) ([]*domain.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []*domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockTaskRepository_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) FindAll(ctx any) *MockTaskRepository_FindAll_Call {
	return &MockTaskRepository_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockTaskRepository_FindAll_Call) Run(run func(ctx context.Context)) *MockTaskRepository_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_FindAll_Call) Return(tasks []*domain.Task, err error) *MockTaskRepository_FindAll_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_FindAll_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Task, error)) *MockTaskRepository_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Save(ctx context.Context, task *domain.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockTaskRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - task *domain.Task
func (_e *MockTaskRepository_Expecter) Save(ctx any, task any) *MockTaskRepository_Save_Call {
	return &MockTaskRepository_Save_Call{Call: _e.mock.On("Save", ctx, task)}
}

func (_c *MockTaskRepository_Save_Call) Run(run func(ctx context.Context, task *domain.Task)) *MockTaskRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Task
		if args[1] != nil {
			arg1 = args[1].(*domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Save_Call) Return(err error) *MockTaskRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Save_Call) RunAndReturn(run func(ctx context.Context, task *domain.Task) error) *MockTaskRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
