// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"

	"github.com/Karbbone/Graefik/apps/api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthenticateUseCase creates a new instance of MockAuthenticateUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthenticateUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthenticateUseCase {
	mock := &MockAuthenticateUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthenticateUseCase is an autogenerated mock type for the AuthenticateUseCase type
type MockAuthenticateUseCase struct {
	mock.Mock
}

type MockAuthenticateUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthenticateUseCase) EXPECT() *MockAuthenticateUseCase_Expecter {
	return &MockAuthenticateUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockAuthenticateUseCase
func (_mock *MockAuthenticateUseCase) Execute(ctx context.Context, token string) (*domain.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthenticateUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAuthenticateUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthenticateUseCase_Expecter) Execute(ctx any, token any) *MockAuthenticateUseCase_Execute_Call {
	return &MockAuthenticateUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, token)}
}

func (_c *MockAuthenticateUseCase_Execute_Call) Run(run func(ctx context.Context, token string)) *MockAuthenticateUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthenticateUseCase_Execute_Call) Return(user *domain.User, err error) *MockAuthenticateUseCase_Execute_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthenticateUseCase_Execute_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.User, error)) *MockAuthenticateUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
