// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package portmocks

import (
	"context"

	"github.com/Karbbone/Graefik/apps/api/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskService creates a new instance of MockTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskService {
	mock := &MockTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskService is an autogenerated mock type for the TaskService type
type MockTaskService struct {
	mock.Mock
}

type MockTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskService) EXPECT() *MockTaskService_Expecter {
	return &MockTaskService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskService
func (_mock *MockTaskService) Create(ctx context.Context, title string) (*domain.Task, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = returnFunc(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockTaskService_Expecter) Create(ctx any, title any) *MockTaskService_Create_Call {
	return &MockTaskService_Create_Call{Call: _e.mock.On("Create", ctx, title)}
}

func (_c *MockTaskService_Create_Call) Run(run func(ctx context.Context, title string)) *MockTaskService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskService_Create_Call) Return(task *domain.Task, err error) *MockTaskService_Create_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskService_Create_Call) RunAndReturn(run func(ctx context.Context, title string) (*domain.Task, error)) *MockTaskService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockTaskService
func (_mock *MockTaskService) List(ctx context.Context) ([]*domain.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockTaskService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskService_Expecter) List(ctx any) *MockTaskService_List_Call {
	return &MockTaskService_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockTaskService_List_Call) Run(run func(ctx context.Context)) *MockTaskService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskService_List_Call) Return(tasks []*domain.Task, err error) *MockTaskService_List_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskService_List_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.Task, error)) *MockTaskService_List_Call {
	_c.Call.Return(run)
	return _c
}
